[project]
name = "ankirec"
version = "1.0.3"
readme = "README.md"
description = "foo bar"
dependencies = ["click", "pynput", "rich", "requests", "mss", "pillow"]

[project.optional-dependencies]
windows = ["soundcard", "soundfile", "pywin32"]
linux = []

[project.scripts]
ankirec = "ankirec.__main__:cli"

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}